export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/search?',
          '/filter?',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
          '/node_modules/',
          '/.git/',
          '/.env',
          '/package.json',
          '/next.config.mjs',
          '/postcss.config.mjs',
          '/tailwind.config.js',
          '/eslint.config.mjs',
          '/jsconfig.json',
          '/README.md',
          '/.gitignore',
          '/public/file.svg',
          '/public/globe.svg',
          '/public/next.svg',
          '/public/vercel.svg',
          '/public/window.svg',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'Slurp',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'DuckDuckBot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'Baiduspider',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'YandexBot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'facebookexternalhit',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'Twitterbot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'LinkedInBot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
      {
        userAgent: 'WhatsApp',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/dashboard/',
          '/login/',
          '/signup/',
          '/checkout/',
          '/cart/',
          '/temp/',
          '/draft/',
          '/backup/',
          '/test/',
          '/dev/',
          '/staging/',
        ],
      },
    ],
    sitemap: 'https://inezhomestay.com/sitemap.xml',
    host: 'https://inezhomestay.com',
  };
}
